### ISSUE TITLE
do we need both python-dotenv and python-decouple?

### ISSUE THREAD

**Issue by bbelderbos** [vnoelifant/movie-search-app#67]
maybe we can stick with latter?

**Comment by vnoelifant** [comment]
Yes, thanks, I prefer python-decouple. Simple IMO.

**Comment by bbelderbos** [comment]
Me too, also does a better job casting booleans.

**Comment by Saunakghosh10** [comment]
yes i too prefer python-decouple

**Comment by vnoelifant** [comment]
Removing references of dotenv
