### ISSUE TITLE
support for non-pipenv

### ISSUE THREAD

**Issue by bbelderbos** [vnoelifant/movie-search-app#68]
I am not using pipenv, I prefer `python -m venv`. I just grabbed the dependencies from Pipfile, but it would be nice to add a requirements.txt file - would you pin the requirements?

**Comment by vnoelifant** [comment]
Sorry, I forgot to do that for this one. I have exported a requirements text file per command `pipenv requirements > requirements.txt` according to https://pipenv.pypa.io/en/latest/advanced/#generating-a-requirements-txt, and will make sure it is up to date if I add more packages.

**Comment by bbelderbos** [comment]
Thanks, you could also use this:

- Using pip-tools to manage Python dependencies: https://www.youtube.com/watch?v=G8PApVvdkjQ │

**Comment by vnoelifant** [comment]
@bbelderbos Thanks for pip-tools reference. I will check out the video. I like the simplicity of venv as well. At the time pipenv was appealing to me due to not having to have to consistently update the pipenv lock file every time as it does it instantly each time a new package is installed.
