### ISSUE TITLE
MultipleObjectsReturned error

### ISSUE THREAD

**Issue by bbelderbos** [vnoelifant/movie-search-app#71]
Can you recommend me @vnoelifant for which movie title / id you get this error please?

![image](https://github.com/vnoelifant/movie-search-app/assets/387927/7bde9abb-920e-4be4-a66f-e95b5ab69cb0)

**Comment by vnoelifant** [comment]
> Can you recommend me @vnoelifant for which movie title / id you get this error please?
> 
> ![image](https://user-images.githubusercontent.com/387927/265769729-7bde9abb-920e-4be4-a66f-e95b5ab69cb0.png)

When the database movies are empty I get it with Indiana Jones on the trending of the day section. 
![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/5a0b487b-9ed6-46cc-8fb6-9f1ba4071aaa)

**Comment by vnoelifant** [comment]
> > Can you recommend me @vnoelifant for which movie title / id you get this error please?
> > ![image](https://user-images.githubusercontent.com/387927/265769729-7bde9abb-920e-4be4-a66f-e95b5ab69cb0.png)
> 
> When the database movies are empty I get it with Indiana Jones on the trending of the day section. ![image](https://user-images.githubusercontent.com/43191157/265779294-5a0b487b-9ed6-46cc-8fb6-9f1ba4071aaa.png)

Also note for the sidebar content (genres, providers) I loaded the fixtures from https://github.com/vnoelifant/movie-search-app/tree/movie-detail-updates/movie_search/fixtures before launching the app.

**Comment by bbelderbos** [comment]
This happens when there are duplicated genres in the DB, specifically here:

<img width="1610" alt="image" src="https://github.com/vnoelifant/movie-search-app/assets/387927/a3b7f7de-020a-4b29-a924-b610e7f71b94">

DB:

<img width="2672" alt="image" src="https://github.com/vnoelifant/movie-search-app/assets/387927/d47cf67a-e157-4590-9dd5-23941a829c5d">

Which is probably caused by running the genre fixture multiple times. So best fix is to make the name column on the search_genre table unique so that there will never be duplicated genre entries. Then you should not hit this issue.

Makes sense?

**Comment by bbelderbos** [comment]
I also had some issues saving the views file so I made this commit: https://github.com/vnoelifant/movie-search-app/commit/5623587bb745d8ebbfe39589b92653fb84d9b16a

**Comment by vnoelifant** [comment]
> This happens when there are duplicated genres in the DB, specifically here:
> 
> 
> 
> <img width="1610" alt="image" src="https://github.com/vnoelifant/movie-search-app/assets/387927/a3b7f7de-020a-4b29-a924-b610e7f71b94">
> 
> 
> 
> DB:
> 
> 
> 
> <img width="2672" alt="image" src="https://github.com/vnoelifant/movie-search-app/assets/387927/d47cf67a-e157-4590-9dd5-23941a829c5d">
> 
> 
> 
> Which is probably caused by running the genre fixture multiple times. So best fix is to make the name column on the search_genre table unique so that there will never be duplicated genre entries. Then you should not hit this issue.
> 
> 
> 
> Makes sense?

Ah yeah, interesting. So with the unique=True field parameter right? I wonder how the fixtures got loaded again. ![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/5dd8121e-002a-4ab2-8c8c-197a7aa68931)

**Comment by bbelderbos** [comment]
Exactly. Please add it to your model, run makemigrations then migrate, then do the fixture import again, I hope it would crash if categories are already found :)

**Comment by vnoelifant** [comment]
Done! Thanks!
