### ISSUE TITLE
are all these fields optional?

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/movie-search-app#72]
are all these fields optional?

_Originally posted by @bbelderbos in https://github.com/vnoelifant/movie-search-app/pull/66#discussion_r1261610838_

**Comment by vnoelifant** [comment]
So in the movie details response documentation, I can't see what is optional or not. I think mostly all are optional except the movie ID, but not sure. Even when I remove the "null=true" and "blank=true" in my movie detail model fields Django complains and gives me the following error. Maybe we can discuss this more in the next code review. 

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/bbbded86-2a7d-42c0-9fc9-c93f12ee4b8f)

**Comment by bbelderbos** [comment]
Yeah maybe we don't have to do anything for now here, is this even an issue right now?

When you write to the table(s) you also generally set defaults no?

More info:

<img width="603" alt="image" src="https://github.com/vnoelifant/movie-search-app/assets/387927/f0e5e75e-e25a-4942-9248-b2049b7c2734">

I usually take option 1 giving it a default value ...
