### ISSUE TITLE
Class refactoring

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/movie-search-app#75]

**Comment by bbelderbos** [comment]
Still clinic pending, but will be nice to already work on the refactoring here before ...

**Comment by bbelderbos** [comment]
Maybe you want to document some of your OOP investigations you did here?

**Comment by bbelderbos** [comment]
... and list the steps you want to take, which parts of the code do you want to refactor into classes and why?

**Comment by vnoelifant** [comment]
Sounds like a good plan @bbelderbos. I will work on that.

**Comment by vnoelifant** [comment]
1. Refactor the tmdb_api.py into a class-based approach.

    - Create a class that encapsulates the functionality for interacting with the TMDB API. This will improve the maintainability and scalability of the code.

2. Refactor media.py: This file handles the logic of communicating with the TMDB API. Refactoring it will involve creating the abstract base class and the specific strategy classes for movies and TV shows.

      -  Abstract Base Classes (ABC): Define an abstract base class for common functionality shared between movies and TV shows. This class will define methods that must be implemented by any subclass.
      
      - Strategy Pattern: Implement separate strategies for movies and TV shows. Each strategy will extend the abstract base class and provide specific implementations for fetching and storing data.


2. Update views.py: This file contains the view logic. It will need to be updated to use the new class-based approach.

3. Models and URLs: models.py and urls.py might require minor updates to align with the refactored code.

**Comment by bbelderbos** [comment]
Nice, ideally this will make your views slimmer. I like ABCs, I used them for pybites-search which I demo'd here: https://www.youtube.com/watch?v=0zROYGLTFKA - repo: https://github.com/PyBites-Open-Source/search
