### ISSUE TITLE
get postgres working locally (to mirror dev <> prod environment)

### ISSUE THREAD

**Issue by bbelderbos** [vnoelifant/movie-search-app#81]
sqlite is fine for starters, but it won't work in most cloud based solutions (including Heroku) because it's file-based

so you'll need postgres and as per best practice it's then also best to mirror your local setup, so yes, please install postgres and then update your .env to point to the db url as commented above, then change settings.py to this:

```
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}
```

_Originally posted by @bbelderbos in https://github.com/vnoelifant/movie-search-app/pull/80#discussion_r1472617995_

**Comment by vnoelifant** [comment]
@bbelderbos I verified I have postgres working locally, however when running my app locally again, I received a 500 error. Doing a bit of research I found that I could run `python manage.py collectstatic`. Running this, the 500 error went away and I can now run my app locally with `Debug=True`. Note that I still have the WhiteNoise Configuration in [settings.py](https://github.com/vnoelifant/movie-search-app/blob/main/config/settings.py). I hope this is the right approach to mirror production environment. It's still a bit fuzzy to me.

**Comment by bbelderbos** [comment]
Hm let's look at this, I don't have to run collectstatic locally ever.

I only have these related settings:

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
...
```

And:

```
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```
