### ISSUE TITLE
Refactor API Access and Parameter Handling for Enhanced Readability and Efficiency

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/movie-search-app#84]
As discussed on call:
- kwargs mixed feelings, but definitely handy at times - FYI https://pybit.es/articles/the-arbitrary-keyword-arguments-args-and-kwargs-dont-come-for-free-in-python/
- fetch_data_from_api / fetch_api_data_by_query are pass-through, they don't add anything causing some duplication, it would be better to use the tmdb_api_obj methods directly
- tmdb_api_obj = TMDBApi() is at module scope, this could be useful for a shared object, but it might be safer to instantiate it in the view = more locally scoped / better namespaced.

_Originally posted by @bbelderbos in https://github.com/vnoelifant/movie-search-app/pull/77#discussion_r1452634031_

**Comment by vnoelifant** [comment]
@bbelderbos I am not quite sure what you mean in the third bullet point above. Can we discuss this on our next call further? Thanks.

**Comment by vnoelifant** [comment]
> [@bbelderbos](https://github.com/bbelderbos) I am not quite sure what you mean in the third bullet point above. Can we discuss this on our next call further? Thanks.

@bbelderbos I was working with the understanding that media.py acts as a service layer between the TMDBApi class (in tmdb_api.py) and views.py. There are many calls in media.py that use tmdb_api_obj methods. So if I instantiate in views.py I think that means I will have to change a lot of code in media.py that uses the tmdb_api_obj. How can I manage this if I move the instantiation of TMDBApi  to views.py?

**Comment by vnoelifant** [comment]
@bbelderbos Curious your take on the recommendation here for handling my concern above. https://chat.openai.com/c/6a7a3432-938a-493f-a769-e1b2587982d8 (dependancy injection, but not too familiar on this).

**Comment by bbelderbos** [comment]
> @bbelderbos I am not quite sure what you mean in the third bullet point above. Can we discuss this on our next call further? Thanks.

This goes back to the risk of using the global namespace ->

1. Global objects can make unit testing more difficult. 

2. Global objects can lead to tight coupling between different parts of an application making code less modular and harder to refactor or extend. 

3. In a multi-threaded application, a single, globally accessible object that was not designed for concurrent access can lead to race conditions and data corruption.

4. Global objects add to the module's global namespace increasing the risk of name collisions (more a thing in larger projects).

Instantiating tmdb_api_obj more locally can lead to better-structured, more testable, and flexible code. However, as this is a relatively small project it probably does not matter too much.

**Comment by bbelderbos** [comment]
> > [@bbelderbos](https://github.com/bbelderbos) I am not quite sure what you mean in the third bullet point above. Can we discuss this on our next call further? Thanks.
> 
> @bbelderbos I was working with the understanding that media.py acts as a service layer between the TMDBApi class (in tmdb_api.py) and views.py. There are many calls in media.py that use tmdb_api_obj methods. So if I instantiate in views.py I think that means I will have to change a lot of code in media.py that uses the tmdb_api_obj. How can I manage this if I move the instantiation of TMDBApi to views.py? I thought having the API methods and related object instantiation outside of views.py was a better separation of concerns, but open to your thoughts if I am missing something!

Let's talk more about this tomorrow looking at the code together ...

**Comment by bbelderbos** [comment]
Regarding args and kwargs, in the case of movie_search/decorators.py `def wrapper(*args, **kwargs):` this is totally common and desired, because you want them to be flexible.

In media.py kwargs is mostly used to pass it through to `get_data_from_endpoint` which then get used in:

```
            params = {"api_key": self.api_key, "language": self.language}
            params.update(kwargs)
            response = requests.get(url, params=params)
```

This is probably fine because the API probably discards extra kwargs. However, if it returns errors for unknown parameters, your method could cause unintended errors. This behavior can vary between different APIs.

It's good to be mindful that **kwargs are less explicit, because anything can be passed into the function and Zen says: explicit is better than implicit.

So yes here it's probably fine and overall **kwargs offer flexibility they could affect usability, clarity, and error handling. Therefore it's good practice to handle and document your use of **kwargs carefully to minimize potential issues.

**Comment by vnoelifant** [comment]
> Regarding args and kwargs, in the case of movie_search/decorators.py `def wrapper(*args, **kwargs):` this is totally common and desired, because you want them to be flexible.
> 
> In media.py kwargs is mostly used to pass it through to `get_data_from_endpoint` which then get used in:
> 
> ```
>             params = {"api_key": self.api_key, "language": self.language}
>             params.update(kwargs)
>             response = requests.get(url, params=params)
> ```
> 
> This is probably fine because the API likely discards extra kwargs. However, if it returns errors for unknown parameters, your method could cause unintended errors. This behavior can vary between different APIs.
> 
> It's good to be mindful that **kwargs are less explicit, because anything can be passed into the function and Zen says: explicit is better than implicit.
> 
> So yes here it's probably fine and overall **kwargs offer flexibility, they can however affect usability, clarity, and error handling.
> 
> Therefore it's good practice to handle and document your use of **kwargs carefully to minimize potential issues.

Thank you @bbelderbos. That is helpful. I have a function called get_movie_discover_data and below I am showing the current implementation and previous implementation for handling its parameters.  I like the idea of using the kwargs to avoid having so many parameters in get_movie_discover_data, but do see how it is less readable. However, you mentioned documenting kwargs is useful. Are you talking about via docstrings? Let me know how you would handle these many parameters in get_movie_discover_data. For me I am thinking keep with kwargs but add docstrings to help explain the parameters (if that is something Pythonistas do with kwargs).  Thanks!

Current implementation:
```
 def get_movie_discover_data(self, **kwargs):
        # Process genres
        genre_names = kwargs.get("genre_names", [])
        genres = self.get_genres_from_discover(genre_names, MovieGenre)

        # Process person
        person_name = kwargs.get("person_name")
        person_id = None
        if person_name:
            person_service = PersonService()
            person_data = person_service.fetch_person_data(person_name)
            person_id = person_service.get_person_id(person_data, person_name)

        # Process providers
        watch_provider_names = kwargs.get("watch_provider_names", [])
        providers = self.get_providers_from_discover(
            watch_provider_names, MovieProvider
        )

        # Update kwargs with processed data
        kwargs.update(
            {
                "with_genres": ",".join(map(str, genres)),
                "with_watch_providers": ",".join(map(str, providers)),
                "with_people": person_id,
            }
        )

        # Remove None values from kwargs
        kwargs = {k: v for k, v in kwargs.items() if v is not None}

        return self.get_discover_data("/discover/movie", **kwargs)

```

Previous implementation (can also have default parameters being equal to None)
```
def get_movie_discover_data(
     genres, person_id, sort_options, region, watch_region, providers, year
):
    return tmdb_api.get_data_from_endpoint(
        "/discover/movie",
        region=region,
        primary_release_year=year,
        with_genres=list(genres),
        sort_by=sort_options,
        watch_region=watch_region,
        with_watch_providers=list(providers),
        with_people=person_id,
    )
```

**Comment by vnoelifant** [comment]
> > [@bbelderbos](https://github.com/bbelderbos) Curious your take on the recommendation here for handling my concern above. https://chat.openai.com/c/6a7a3432-938a-493f-a769-e1b2587982d8 (dependancy injection, but not too familiar on this).
> 
> Can you share again? I cannot load this conversation ...

https://chat.openai.com/share/239bb121-48bd-4197-af57-2dc8fbb239f0. Not sure if you can see that update, but in the PR #85 I added a couple of screenshots of the chat. Thanks!

**Comment by vnoelifant** [comment]
> Regarding "tmdb_api_obj = TMDBApi() is at module scope" we were talking about today ...I cannot share the GPT thread because it contained a screenshot so here is additional info related to what I explained on our call today:
> 
> <img alt="image" width="692" src="https://private-user-images.githubusercontent.com/387927/319690956-7ced2f40-086f-45aa-be63-19b99b11805d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDI2OTEsIm5iZiI6MTcxMjM0MjM5MSwicGF0aCI6Ii8zODc5MjcvMzE5NjkwOTU2LTdjZWQyZjQwLTA4NmYtNDVhYS1iZTYzLTE5Yjk5YjExODA1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxODM5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjEzYmQ1NzM1ZmZkNzlkNzhlOWIwYmJkZGJmM2RhNzk5MDkzNTA4YTk5YmU2Y2EwZWEzMTllOGU0OTM1ODY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.REpG1nEA5_rngDMA99-Z3TdDH4q3Z9F_SR5qHkiKQFg">
> and
> 
> <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/387927/319691578-ec137202-6363-42cf-9fd3-5c743e4e84a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDI2OTEsIm5iZiI6MTcxMjM0MjM5MSwicGF0aCI6Ii8zODc5MjcvMzE5NjkxNTc4LWVjMTM3MjAyLTYzNjMtNDJjZi05ZmQzLTVjNzQzZTRlODRhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxODM5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmRkYzAzOGI2ZDIyZmI5MDc2ZmY5ZDIyOWY3OTBjYzg4ZDk5NDhkMmZlOGVmNzUxOTk0YzI2NDRhZDhhOTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.utl0dSUz1a-T9Hbn5AgsVz8Sia4JZznearII_7aHPqo">
> Makes sense? Let me know if you have any follow up questions about this interesting topic.

@bbelderbos Very interesting, thanks! How can I determine whether this media app needs to be stateless or not? Any questions I should ask myself to determine this? I do know that I'd like flexibility for users to select different query parameters, (i.e. language, year, etc). I think I am leaning toward a middleware to attach query parameters to the request object. https://docs.djangoproject.com/en/5.0/topics/http/middleware/

**Comment by vnoelifant** [comment]
@bbelderbos I know you mentioned try to remove the pass through methods that were in media.py as per your first comment in this issue, however I am encountering a situation where I have a mixture of calling the methods of the TMDBApi class in tmdb_api.py directly in views.py, and also accessing those methods via the service layers defined in media.py. I am looking for a balance between keeping API interactions in media.py, but also avoiding pass-through methods there as well. Here is some GPT research. Let me know your thoughts!

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/04d352aa-74d5-4824-a172-3be0c1bb2784)

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/7b1db984-1361-4b2b-8e5c-a0ebf934b208)

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/30c1a52f-188d-4ae2-a7cd-b1ecc496049f)

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/493ffbee-8dc9-43bd-839a-9d1b6f57c7ba)

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/bc1c1f71-84bb-4a15-a7e5-b4884743c856)

![image](https://github.com/vnoelifant/movie-search-app/assets/43191157/c6d4a6b2-a861-4ff8-8c7d-738b9c245572)

**Comment by bbelderbos** [comment]
Thanks for the research, maybe easier to discuss on a call, shall we meet shortly later this week?

**Comment by vnoelifant** [comment]
> Thanks for the research, maybe easier to discuss on a call, shall we meet shortly later this week?

Yeah that sounds good.  I can meet anywhere from 2-3 pm (7-8 am my time). @bbelderbos

**Comment by bbelderbos** [comment]
Great, I sent you an invite for Friday, talk then!
